# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=docx-converter

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: docx-pdf-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/docx-converter
      - PORT=5000
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/usr/src/app/uploads

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docx-pdf-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    depends_on:
      - backend

volumes:
  mongodb_data: