# kubernetes/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: docx-pdf-frontend-service
spec:
  selector:
    app: docx-pdf-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer