# kubernetes/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docx-pdf-frontend
  labels:
    app: docx-pdf-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docx-pdf-frontend
  template:
    metadata:
      labels:
        app: docx-pdf-frontend
    spec:
      containers:
      - name: frontend
        image: docx-pdf-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: VITE_BACKEND_URL
          value: http://docx-pdf-backend-service:5000
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi